exclude: &excludes '^(frontend/node_modules/|backend/node_modules/|frontend/build/|backend/venv/)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: *excludes
    -   id: end-of-file-fixer
        exclude: *excludes
    -   id: check-yaml
        exclude: *excludes
    -   id: check-added-large-files
        exclude: *excludes
    -   id: detect-private-key
        exclude: *excludes

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: *excludes
        additional_dependencies: ['gibberish-detector']

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.22.1
    hooks:
    -   id: gitleaks
        exclude: *excludes
